-- Create tables for Turso

CREATE TABLE IF NOT EXISTS Post (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    summary TEXT,
    content TEXT NOT NULL,
    published INTEGER NOT NULL DEFAULT 0,
    date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Tag (
    id TEXT PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Idea (
    id TEXT PRIMARY KEY,
    text TEXT NOT NULL,
    completed INTEGER NOT NULL DEFAULT 0,
    createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS _PostToTag (
    A TEXT NOT NULL,
    B TEXT NOT NULL,
    FOREIGN KEY (A) REFERENCES Post(id) ON DELETE CASCADE,
    FOREIGN KEY (B) REFERENCES Tag(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS _PostToTag_AB_unique ON _PostToTag(A, B);
CREATE INDEX IF NOT EXISTS _PostToTag_B_index ON _PostToTag(B);
